### ISSUE TITLE
Where is Dapr.Messaging?

### ISSUE THREAD

**Issue by maxiptah** [dapr/dotnet-sdk#1402]
I wanted to follow this example to programmatically subscribe to topics: https://github.com/dapr/dotnet-sdk/blob/master/examples/Client/PublishSubscribe/StreamingSubscriptionExample/Program.cs

That would be a streaming subscription in Dapr terms.

I've installed I think all nuget Dapr packages, but I don't get access to Messaging namespace.
Method `builder.Services.AddDaprPubSubClient();` is not available.

**Comment by WhitWaldo** [comment]
It will be distributed on NuGet with the 1.15 release in about a month, but it's a brand new package.

If you've cloned the .NET SDK repo (as it appears you have), you can find it at /src/Dapr.Messaging and that example _should_ work given that it uses a project reference instead of a NuGet package.

**Comment by maxiptah** [comment]
Ok, thank you for the info! Thought so, but was confused by some posts on the Internet that said it's a feature in 1.14.

Basically, my use case was creating subscriptions once on application start programmatically. The list of topics was coming from a configuration file. So I searched for a dynamic way to create them because the official way in the [docu](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#streaming-subscriptions) would be with an attribute: `app.MapPost("/orders", [Topic("pubsub", "orders")] (Order order) => {});` This of course makes dynamic creation impossible, as you cannot use variables in attributes.

However, this worked for me: `app.MapPost("/orders", (Order order) => {}).WithTopic("pubsub", "orders");`. Is there a potential problem with this approach? If not, it would probably be nice to point out this possibility in the docs.

**Comment by WhitWaldo** [comment]
@maxiptah Yes, the feature itself was released on the Dapr runtime itself in 1.14 and if you're using the HTTP or gRPC APIs directly, you can start using it today. But if you're wanting to use the .NET SDK that simplifies using this new capability, that will come with the 1.15 release in early December. It's already merged, as you noted in the repository, but just because the example, documentation and SDK bits are in master, we haven't actually cut a release to NuGet yet with the new package.

That approach is just using the existing subscription capability. I agree - the docs could use some updates to better reflect the difference between the three approaches (configuration, static programmatic and dynamic programmatic (new)) and I'll see what I can get done before the release next month on that front. Using the topic attribute means that if you want to subscribe to new topics, you're going to need to rebuild the application. That's more than fine and it's been how this works to date, but the new capability lets you programmatically subscribe to new topics on the fly without a recompilation - just know the name of the component and your queue/topic and provide the necessary handler to process the inbound messages.

To your point, no, I don't see anything wrong with using that approach if it's working for you.

@theperm Yes, there's nothing dynamic about specifying `WithTopic` in the configuration, but that's also not the new capability. We've had that for at least a couple of years. The new capability is described [here](https://v1-15.docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#streaming-subscriptions) using the Go SDK (.NET docs [are pending](https://github.com/dapr/docs/pull/4358/files)) and needs no app recompilation/restart.

If you want to use a configuration-style, that's a supported option as well and documented [here](https://v1-15.docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#declarative-subscriptions) with hot-reload preview support.

**Comment by WhitWaldo** [comment]
I'm going to go ahead and close this issue as the question has been answered, but feel free to either re-open with any follow-ups or open another issue as needed.
