### ISSUE TITLE
What is the best place to validate actor id?

### ISSUE THREAD

**Issue by wanton7** [dapr/dotnet-sdk#254]
I would like to validate that actor id is in Guid.ToString("N") format and stop actor activation if actor id is not in valid format. Is it ok to validate actor id in actor's constructor and throw exception, that should stop actor activation right? Or is there a better way to do it?

**Comment by amanbha** [comment]
@wanton7 yes, that would do it, but I would not suggest it and want to understand your scenario for it. For almost every application leveraging the actor pattern, the client is controlled by the application developer when they make calls to the actor, so the best place to restrict it when you are calling actor service from client side rather than throwing exception form server side.

**Comment by wanton7** [comment]
I'm currently parsing ActorId back to Guid that I use in other places. Maybe my my design is flawed and I should actually store that Id to actors state when state is created the first time and let ActorId be anything?

**Comment by codeputer** [comment]
I may be wrong in my assessment of an Actor Id, but I thought I would jump in in this discussion to discuss.

I see the thinking of an appropriate Actor Id in the same way I think about natural and surrogate keys in relational theory.

Selection of a natural key is easily used, but often comes with the issue of change.  For example, a phone number is a good natural key, but in reality, it can change.  So using it rather than a surrogate key is a trade off.

In my solution I use 2 actors... 1 actor is the surrogate key, the other actor is the Mapping Actor... Where natural keys are mapped to the "internal" customer actor identified by a surrogate key (eg. guid)

This solves the who validates what problem (IMO), but creates a concurrency issue when Actors use turned base concurrency for read activity.

All calls must be routed through the Mapping Actor, or do the orchestration in the client.

In Service Fabric the Mapping of natural key to surrogate was a service...not sure about the implementation of the same concept in Dapr... But that is likely another discussion
