### ISSUE TITLE
Create documentation and samples for the Secret Store configuration provider implementation

### ISSUE THREAD

**Issue by cmendible** [dapr/dotnet-sdk#256]
## Describe the proposal

Create documentation and samples for the Secret Store configuration provider implementation described in #238

**Comment by amanbha** [comment]
@cmendible since Secret store configuration cannot be used with aspnet core currently due to the requirement that app must start a server before secret api is available in runtime. Would it be ok, if we stop building the Dapr.Extensions.Configuration.csproj project and dotn publisht he nuget for it unless it works out of the box.

**Comment by amanbha** [comment]
closing the issue until we resurrect the secret store configuration provider.
