### ISSUE TITLE
Allow to pass W3C trace header or grpc-trace-bin to dapr api call

### ISSUE THREAD

**Issue by youngbupark** [dapr/dotnet-sdk#300]
## Describe the proposal

Allow to pass W3C trace header(`traceparent`) or `grpc-trace-bin` to dapr api call.

0.7.0 supports traceparent and grpc-trace-bin. Dotnet-sdk needs the way to pass `traceparent` for http or `grpc-trace-bin` metadata for grpc.

**Comment by youngbupark** [comment]
@shalabhms @amanbha @LMWF It would be good to think about how to allow users to use their own trace id in dotnet-sdk, but I understand there were no strong requests from customers.

**Comment by rynowak** [comment]
.NET Core 3.0+ will propagate the W3C header format by default if the appropriate headers are set on the inbound request. It's also a good idea overall to add the guidance to set [this property](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.defaultidformat?view=netcore-3.1#System_Diagnostics_Activity_DefaultIdFormat) to the W3C value in `Main()` if you're using W3C tracing - this way we create a new trace ID for the request if one wasn't passed in.

- Request comes in: ASP.NET Core parses the header and sets [Activity.Current](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.current?view=netcore-3.1)
- Activities are ambient (like thread-local but async-aware) so once its set by the server it's applied to all processing triggered from that request.
- `HttpClient` knows about `Activity.Current` and will automatically apply the headers to any outbound calls if the ID is set.

If you want to customize the ID then typically I think you'd set `HttpContext.TraceIdentifier` as well as `Activity.Current.Id`.  I'm not sure if we have to do anything here specially because we're doing gRPC.

This whole flow should be fairly automatic since these features are built-in to .NET as a platform. I'm surprised if it's not already working :laughing:

/cc @noahfalk @shirhatti @jamesnk

**Comment by LMWF** [comment]
Need to validate

**Comment by shalabhms** [comment]
> Need to validate

@LMWF , this has been validated . Need to have workaround fix https://github.com/dapr/dapr/pull/1816 for the scenario to work. You can find the zipkin trace image for the test in the PR.

**Comment by amanbha** [comment]
dapr runtime added a workaround until grpc-dotnet client is fixed.
