### ISSUE TITLE
Add Integration tests to .net sdk repo

### ISSUE THREAD

**Issue by vinayada1** [dapr/dotnet-sdk#389]
## Expected Behavior

Add integration tests that can be run end-to-end on every PR.

## Actual Behavior

No end-to-end tests

**Comment by vinayada1** [comment]
Especially actors

**Comment by rynowak** [comment]
I added a project for in-memory integration tests as part of the DI pr - so we're unblocked for writing tests that don't use the Dapr sidecar. However it would be even better if we can include the interactions with `daprd` like the Java SDK does. We've definitely seen bugs where drift between our expectations and the behavior of `dapr` was the root cause.

**Comment by rynowak** [comment]
Closing this because it has no actionable information. We'll add tests as we make changes and investments going forward.
