### ISSUE TITLE
Prefer IDictionary<TKey, TValue> over Dictionary<TKey, TValue> in public APIs

### ISSUE THREAD

**Issue by philliphoff** [dapr/dotnet-sdk#395]
The `DaprClient` class (among others) has [methods](https://github.com/dapr/dotnet-sdk/blob/bf0354bd39ed4af508f95e9c3ab3e9fa30266887/src/Dapr.Client/DaprClient.cs#L52) which accept concrete `Dictionary<TKey, TValue>` arguments.  Instead, the interface type `IDictionary<TKey, TValue>` should be preferred in order to widen the set of dictionary-like types that can be passed by callers.  (You might even consider `IReadOnlyDictionary<TKey, TValue>` to help signify that the argument isn't modified by the call but, while this would likely generally work, there are dictionary-like types that do not support the relatively newer `IReadOnlyDictionary<TKey, TValue>` interface, so `IDictionary<TKey, TValue>` is likely a reasonable compromise).

**Comment by rynowak** [comment]
Which other dictionary type do you want to use?

**Comment by philliphoff** [comment]
@rynowak At the moment, I don't have a specific need for a type *other* than `Dictionary<TKey, TValue>`, but I could imagine wanting to use something like [`ImmutableDictionary<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary-2?view=netcore-3.1), which currently wouldn't work (but could, if the interface was used in the API rather than the concrete type).

It was just something I noticed about the API as I was using it.

**Comment by rynowak** [comment]
In my experience the advice about "prefer interfaces over concrete types" isn't super useful with dictionary because:

- it's **exceedingly** rare to have a custom dictionary implementation 
- they messed up and made `IDictionary<>` not inherit `IReadOnlyDictionary<>`

So if you accept `IDictionary` you cannot pass that into anywhere that accepts `IReadOnlyDictionary<>` and vice-versa. My perspective is that if you make an API that accepts `IDictionary<>` you're usually hurting yourself. I say this as the author of the most useful `IDictionary<>` [implementation](https://github.com/dotnet/aspnetcore/blob/master/src/Http/Http.Abstractions/src/Routing/RouteValueDictionary.cs) around 🤣 

For our purposes `IReadOnlyDictionary<>` is probably the right thing to do since we don't modify the metadata 👍 - I wanted to see if you had an actual concrete use case. Changing to `IReadOnlyDictionary<>` seems like a good tradeoff because it lets us communicate about the contract.

**Comment by philliphoff** [comment]
I'd be perfectly ok with `IReadOnlyDictionary<TKey, TValue>`; as you said, it's a good mix between flexibility of data types while helping indicate how the data will be used (i.e. it won't be mutated).
