### ISSUE TITLE
Timers invocation fails after app restarts

### ISSUE THREAD

**Issue by artursouza** [dapr/dotnet-sdk#435]
## Expected Behavior

After the app crashes (not Dapr sidecar), Actor timers should continue to be fired successfully.

## Actual Behavior

After the app crashes, the context of all registered timers is lost . See: https://github.com/dapr/dotnet-sdk/blob/26651756d0ca997218fa3a89b18b153326649b39/src/Dapr.Actors/Runtime/Actor.cs#L29

## Steps to Reproduce the Problem

Start the app that has an Actor.
Start Dapr sidecar.
Invoke a method in Actor that will register a timer.
See timer being logged in App.
Restarted App.
See exception when trying to trigger timer in App.

## Release Note

RELEASE NOTE: **FIX** Timer invocation after Actor runtime app restarts.

**Comment by rynowak** [comment]
This will be an impactful change. The dotnet SDK allows you to register an arbitrary `Func<object, Task>` as a timer.

```
protected async Task<IActorTimer> RegisterTimerAsync(
            string timerName,
            Func<object, Task> asyncCallback,
            object state,
            TimeSpan dueTime,
            TimeSpan period)
{
}
```

There's no way that an arbitrary `Func<>` object can be serialized and restored from memory because it could be a closure holding on to arbitrary state.

Two approaches emerge:

- Require the callback to refer to a non-overloaded instance/static method declared on the actor type (or its base-class hierarchy) - this would be equivalent to registering a callback by name. This is the approach the Java takes.
- Requires the Actor class to associate timer names with functions during the `OnActivatedAsync` lifecycle method. No timers would be started at this point - only the associations between timer names and callbacks. The `RegisterTimerAsync` method would no longer accept a callback. The side effect would be that it its no longer possible to dynamically register a timer with a generated name.

Personally, I think the first option is a little bit more primitive, but it's simpler to reason about from a user's POV. The second options requires users to understand more about how timers work under the covers.

**Comment by vinayada1** [comment]
@amanbha  - Are you aware of the history why we used delegates?

**Comment by amanbha** [comment]
> @amanbha - Are you aware of the history why we used delegates?

Delegate seemed more user friendly, rather than just taking a method name and it follows Servic3e Fabric actor model.
Ideally, timers should not survive a restart as they are not persisted.

**Comment by artursouza** [comment]
@amanbha The problem observed here is when the app crashes and is restarted. User do not expect timer to be "gone" after that. The side effect was that there were errors for dapr sidecar triggering a timer that the app was not aware of.

**Comment by amanbha** [comment]
> @amanbha The problem observed here is when the app crashes and is restarted. User do not expect timer to be "gone" after that. The side effect was that there were errors for dapr sidecar triggering a timer that the app was not aware of.

Got it, my understanding is that timers should not survive any restart whether app or sidecar.

Given the current situation, there are 2 ways forward:
1. Timers will not survive any restart, and Dapr can also unregister timer in case app restarts and it gets an error form app.
2. Timers survive app restart, in this case a delegate will not work, In this case solutions are what Ryan mentioned above. It can be similar to how Reminders work, timer calls are sent to a ReceiveTimerAsync method. This option would be a breaking change

**Comment by artursouza** [comment]
@amanbha From the feedback from user (we can sync offline about the user), expectation is on path 2.
