### ISSUE TITLE
Provide alternatives for raw bytes in all Dapr Client APIs and remove automatic protobuf serialization

### ISSUE THREAD

**Issue by akkie** [dapr/dotnet-sdk#442]
Currently Dapr internally used serialization/deserialization in different components. It uses it in the DaprClient, in the Actor and I think also in the state implementation. For all the components the JSON serialization options can be set at different places. I propose a single serializer implementation that can be reused internally by Dapr and which easily allows the user to set the JSON serialization/deserialzation option once. The serializer implementation should also be exposed so that the internal serialization/deserilzation logic can be used in user code to enable gRPC APIs.

There exists currently two open issues:
https://github.com/dapr/dotnet-sdk/issues/362
https://github.com/dapr/dotnet-sdk/issues/441

I think this could be implemented as proposed in https://github.com/dapr/dotnet-sdk/pull/440 but with a more general approach. As example by implementing a `DaprSerializer` which can handle all the possible serialization/deserialization tasks.

**Comment by rynowak** [comment]
Thanks @akkie for opening this and #441 per my request for discussion. I'm responding here, because this issue seems to also include addressing #441 inside its scope. I agree that this area can be improved and there are a lot of variables to discuss because there are many possible solutions.

### Background

Some background my POV as a long time contributor to the Dapr dotnet-sdk....

Early on we took a dependency on System.Text.Json in the dotnet-sdk and added a bunch of methods that use JSON serialization to interact with the Dapr sidecar (over HTTP). This seemed like the obvious thing to do because it was both convenient and useful. 

Since then we've seen features related to gRPC come online, the transport used in dotnet-sdk has swapped from HTTP->gRPC, and we've seen that *other* SDKS for Dapr expose the ability to work with raw bytes.

The truth is that it was bytes all along, but the dotnet-sdk has really biased its API surface towards JSON and specifically `System.Text.Json`. 

At some point the code to handle `IMessage`-implementing types specially using Protobuf got added, because that seemed like the simplest thing to do for gRPC cases. At this point it would be fair to say that the dotnet-sdk now has *"serialization logic"* - whereas before this point we just called a static method.

The point I want to make is that it was never a goal to have *serialization logic*. Dapr is for interoperability, and the thing that matters most in that regard is clarity and predictability.  Piggybacking on top of a well-known and documented implementation without layering our own logic is the best way to have clear behavior.

### Concerns

My main concern is that I think the idea of a *Dapr serializer* as an extensibility point that comes with the wrong assumptions.

- The data format used to communicate with another service can't be treated as an implementation detail, it's a contract. It would be harmful to build up a base of complex logic in the dotnet-sdk that users take a dependency on without understanding.
- It's not guaranteed that each app has a *single* serializer - you might use protobuf to talk to service A, XML to talk to service B, and JSON to talk to the state store
- It's not guaranteed that `IMessage` <-> protobuf ([see here](https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/json-formatter)). As soon as you consider a 3rd format - the idea that you can map .NET types <-> serialization formats from a single extensibility point breaks
- It's not clear what an API would look for a serializer that provides the right context to implement the above 
- The escape hatch when you can't have a single serializer abstraction is to have multiple instances of `DaprClient` to juggle, which seems complicated.

### An alternative

My alternative to what's being proposed here:

- We're in the process of adding a 'raw' method that works with unopinionated bytes. Once that's in the layering is improved and it's possible to do anything.
-We Separate the functionality that deals with Protobuf from the functionality that deals with JSON. `InvokeMethodJsonAsync()` vs `InvokeMethodProtoAsync` vs `InvokeMethodRawAsync`. This is the similar to the pattern that we followed with `HttpClient`+JSON.
- We add overloads to all of the "JSON" methods that allow passing in an ad-hoc serializer `JsonSerializerOptions` for one-off customization
- We add additional "raw" methods where needed to expose working with bytes as a first class feature - Dapr isn't really coupled to JSON
- We **do** add a single place to configure the default `JsonSerializerOptions` for all Dapr features including actors (this will be a very impactful change).
- We **do** expose the functionality for converting an object to/from a json-serialized `Any` for use with gRPC. This is just minor glue code, but it will make people's lives more convenient.


It's likely we'll need some more discussion on this possibly including some other maintainers. Other SDKs have similar serialization logic to what dotnet-sdk does today (and some don't). There's no statement that we *need* to have all the SDKs behave the same, but it needs to be easy to reason about across languages.

**Comment by akkie** [comment]
@rynowak Thanks for sharing your thoughts. I completely agree with your points. I think having the other SDK maintainers on board would be really helpful, because in my opinion it should be guaranteed, that if I call a go Dapr service from a .NET Dapr service, that the internal data transformation logic should work in both ways.

**Comment by rynowak** [comment]
@akkie - I just want to confirm one thing - you don't actually *need* a replaceable serializer abstraction right? You just want this area to be more sensible in general 😆

**Comment by amanbha** [comment]
I agree, adding method overloads to work with bytes would be a good addition and allows for greater flexibility to users for serialization/deserialization.

**Comment by akkie** [comment]
@rynowak No, I don't need that actually 😉 Yea, but would be great if we find a good solution

**Comment by rynowak** [comment]
## Proposal

Here's a refined proposal after some discussion with the team. I'm showing a simplified set of overloads here to avoid there being an overwhelming amount of stuff to discuss. The main idea is to make it clear what form of serialization (including none) is used from the method name.

```C#
namespace Dapr.Client
{
    public abstract class DaprClient
    {
        // These methods serialize the request and response as JSON using the System.Text.Json serializer.
        //
        // We expect this to be the most common case by far so these methods have the simplest name.
        public abstract ValueTask<TResponse> InvokeMethodAsync<TRequest, TResponse>(
            string appId,
            string methodName,
            TRequest data,
            Dapr.Client.Http.HTTPExtension httpExtension = default,
            CancellationToken cancellationToken = default);

        public abstract Task<InvocationResponse<TResponse>> InvokeMethodWithResponseAsync<TRequest, TResponse>(
            string appId,
            string methodName,
            TRequest data,
            Dapr.Client.Http.HTTPExtension httpExtension = default,
            CancellationToken cancellationToken = default);


        // These methods performs NO serialization.
        // 
        // These can be used as a building block for other APIs (extension methods) or can be used for non-textual data
        public abstract Task<byte[]> InvokeMethodRawAsync(
            string appId,
            string methodName,
            byte[] data,
            Dapr.Client.Http.HTTPExtension httpExtension = default,
            CancellationToken cancellationToken = default);

        public abstract Task<InvocationResponse<byte[]>> InvokeMethodRawWithResponseAsync(
            string appId,
            string methodName,
            byte[] data,
            Dapr.Client.Http.HTTPExtension httpExtension = default,
            CancellationToken cancellationToken = default);


        // These methods use Protobuf to serialize data. These are useful for communicating with a gRPC service
        // that's using Protobuf.
        public abstract ValueTask<TResponse> InvokeMethodProtobufAsync<TRequest, TResponse>(
            string appId,
            string methodName,
            TRequest data,
            Dapr.Client.Http.HTTPExtension httpExtension = default,
            CancellationToken cancellationToken = default)
        where TRequest : IMessage, TResponse : IMessage;


        public abstract Task<InvocationResponse<TResponse>> InvokeMethodProtobufWithResponseAsync<TRequest, TResponse>(
            string appId,
            string methodName,
            TRequest data,
            Dapr.Client.Http.HTTPExtension httpExtension = default,
            CancellationToken cancellationToken = default)
        where TRequest : IMessage, TResponse : IMessage;
}
```

## FAQ 

### There are 6 methods defined here - is that it? 

The other variation is the other flavours of `InvokeMethodAsync`:

- void (no request body, no response body)
- TRequest (serialize request body, no response body)
- TResponse (no response body, deserialize response body)
- TRequest, TResponse (serialize request body, deserialize response body)

We'd end up with 16 total:

- void: `InvokeMethodAsync`, `InvokeMethodWithResponseAsync`, `InvokeMethodRawAsync`, `InvokeMethodRawWithResposneAsync`
- TRequest: `InvokeMethodAsync`, `InvokeMethodWithResponseAsync`, `InvokeMethodProtobufAsync`, `InvokeMethodProtobufWithResponseAsync`
- TResponse: `InvokeMethodAsync`, `InvokeMethodWithResponseAsync`, `InvokeMethodProtobufAsync`, `InvokeMethodProtobufWithResponseAsync`
- TRequest, TResponse: `InvokeMethodAsync`, `InvokeMethodWithResponseAsync`, `InvokeMethodProtobufAsync`, `InvokeMethodProtobufWithResponseAsync`

For invoke, we'd provide these 6 shapes with all of the combinations of inputs and outputs.

### Would we provide these methods for every building block?

We can provide this variety when it makes sense. Fundamentally the Dapr building blocks aren't coupled to a serialization format, JSON is just the most common.

I could see us (for example) skipping the Protobuf related functionality for other building blocks besides invoke.

**Comment by rynowak** [comment]
Renamed the issue to reflect the action we plan to take.
