### ISSUE TITLE
Use Task instead of ValueTask

### ISSUE THREAD

**Issue by amolenk** [dapr/dotnet-sdk#517]
We should replace the use of `ValueTask` in the `DaprClient` with `Task`. 

The API mostly follows the pattern of using `Task` when the return type is `void`, and `ValueTask<TResult>` when the method returns some value (even though there's also a non-generic `ValueTask` available). For example:

```csharp
public abstract Task InvokeMethodAsync(string appId, string methodName, HttpInvocationOptions httpOptions = default, CancellationToken cancellationToken = default);

public abstract ValueTask<TResponse> InvokeMethodAsync<TRequest, TResponse>(string appId, string methodName, TRequest data, HttpInvocationOptions httpOptions = default, CancellationToken cancellationToken = default);
```

However, this pattern is not 100% consistent, for example, the following method returns a `InvocationResponse<TResponse>`, but it does use `Task`:

```csharp
public abstract Task<InvocationResponse<TResponse>> InvokeMethodWithResponseAsync<TRequest, TResponse>(string appId, string methodName, TRequest data, HttpInvocationOptions httpOptions = default, CancellationToken cancellationToken = default);
```

The reason why `ValueTask<TResult>` was added to .NET Core is mainly to be able to write an async method that can complete synchronously without incurring additional allocations. However, each of the `DaprClient` API methods has to make a network call to the Dapr sidecar. 

According to [Stephen Toub’s blogpost on ValueTasks](https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/?WT.mc_id=ondotnet-c9-cxa#should-every-new-asynchronous-api-return-valuetask-valuetasktresult), the default choice should still be `Task` / `Task<TResult>`. His main point is that `Task` and `Task<TResult>` are easier to use correctly than `ValueTask`/`ValueTask<TResult>`. So unless the performance implications outweigh the usability implications (which I believe don’t, because of the async sidecar calls), `Task` / `Task<TResult>` are still preferred.

**Comment by rynowak** [comment]
Thanks for starting a discussion @amolenk 

I think the patchwork different choices here is in part due to many people being involved with implementing the .NET SDK and the someone lax approach we've taken to API design.

> However, this pattern is not 100% consistent

To be really clear and up front, I don't place much value on consistency in a case like this. `Task` and `ValueTask` are intended to be virtually identical from the POV of a consumer. If you're doing something different than `await` then you're in a special case 😆 

However, I think you might be right that there's no real benefit to ValueTask for our use cases. ValueTask *can* be misused but that's already been mitigated by an *on-by-default* analyzer as of SDK 5.0 https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2012

> According to Stephen Toub’s blogpost on ValueTasks, the default choice should still be Task / Task<TResult>. His main point is that Task and Task<TResult> are easier to use correctly than ValueTask/ValueTask<TResult>. So unless the performance implications outweigh the usability implications (which I believe don’t, because of the async sidecar calls), Task / Task<TResult> are still preferred.

I've seen (and sometimes argued) multiple versions of this debate internally to the .NET Core team both before and after this blog post was published. One of the biggest barriers to ValueTask being introduced in the first place was the fear of misuse since it doesn't fulfill the exact same contract of Task. This largely hasn't been an issue, and the use of ValueTask and it's capabilities has grown. 

I think at this point if I were starting from scratch I would probably choose Task for simplicity. There's a lot of parallels with the HttpClient + JSON APis that were added in .NET 5 and we decided on Task for those (for reasons I don't recall). However at this stage of the game if we're making a change to use Task everywhere I want to make sure it's the right one, and that we're not going to regret it later. I'll follow up with some folks offline and try to get confirmation about the tradeoffs.

**Comment by amolenk** [comment]
Hi @rynowak 

Thanks for the detailed response. I'm very interested to hear any conclusions from the offline discussions about how to make these tradeoffs.

**Comment by rynowak** [comment]
The conclusion of this from talking to @terrajobst was that info in that blog post is current. 

Overall if can't avoid the asynchrony and we're not going to implement some of the specialized optimizations that `ValueTask<>` can support, it might end up being more expensive.

**Comment by rynowak** [comment]
Thanks @amolenk
