### ISSUE TITLE
Why does GetStateAndETagAsync exist?

### ISSUE THREAD

**Issue by amolenk** [dapr/dotnet-sdk#525]
## Ask your question here

What's the reasoning behind the `GetStateAndETagAsync<TValue>` method? It seems unnecessary because you can already use the `GetStateEntryAsync<TValue>` method to get the value with the associated ETag. 

update:
Thinking about this some more. Would it make sense to only use `StateEntry` in the context of ASP.NET model binding, and make `GetStateEntryAsync<TValue>` internal? This would eliminate any confusion on which method to use when you directly use `DaprClient`.

Update via `DaprClient`:
```c#
var (value, etag) = await daprClient.GetStateAndETagAsync<WeatherForecast>("statestore", city);

// ... make some changes to the retrieved value

await daprClient.TrySaveStateAsync("statestore", city, value, etag);
```

Update via modelbinding:
```c#
[HttpPut("{city}")]
public async Task Put(WeatherForecast updatedForecast, [FromState("statestore", "city")] StateEntry<WeatherForecast> currentForecast)
{
    currentForecast.Value = updatedForecast;

    var succes = await currentForecast.TrySaveAsync();
    // ... check result
}
```

@rynowak Any thoughts on this? ;-)

**Comment by rynowak** [comment]
@amolenk - this exists so that the state APIs support both an object-oriented (`StateEntry`) and a non-object-oriented pattern for interaction. `StateEntry` is an additional concept that doesn't really exist in Dapr, it only exists in the .NET SDK. All of the other API are simpler in that they map directly to how the state APIs work.

I'm going to close this because I don't see any reason to change this, the layering is really simple and this gives users a choice if they prefer the OO or non-OO pattern for managing state.
