### ISSUE TITLE
Encryption of actor state

### ISSUE THREAD

**Issue by grahamehorner** [dapr/dotnet-sdk#548]
Please consider supporting actor state encryption, actor state may have confidential or personal data that requires to be secured at rest and in transit by regional laws.  Dapr actor state should be encrypted when persisted or set over the wire to a node within the cluster using removing so to protect data for unauthorised parties and wiring sniffing

**Comment by rynowak** [comment]
Thanks for starting a discussion @grahamehorner - if you're interested in this topic, it might be better to start a discussion on dapr/dapr - because it seems unlikely to me that we're going implement an encryption feature inside the .NET SDK.

Dapr already supports mutual TLS for data exchanged between sidecars, and many state stores will already have encryption at rest built in.

If there are any changes needed for Dapr to meet compliance requirements, the work is likely to originate from the runtime layer so that features can:

- Apply to any language, including those without a rich SDK
- Share as much of the implementation/behavior as possible

**Comment by artursouza** [comment]
@rynowak Can we move this to dapr/dapr repo?

**Comment by yaron2** [comment]
This is tracked in https://github.com/dapr/dapr/issues/1090

**Comment by yaron2** [comment]
Closing

**Comment by artursouza** [comment]
Maybe this can be closed.

**Comment by rynowak** [comment]
Yup. ideally this is implemented in dapr runtime and the SDKs dont' need to do any work for you to use it.
