### ISSUE TITLE
Simplifying Service Invocation API surface

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#549]
## Background

We're making changes broadly across Dapr to rely on HTTP for service invocation: https://github.com/dapr/dapr/issues/2342

Currently the SDK relies on gRPC for service invocation, which means that in the common path HTTP responses have to be translated to gRPC responses. This translation layer has some technical challenges since the error handling model is gRPC is very simple compared to HTTP. It also means at the .NET SDK has to abstract over the different behaviors of protocols - treating semantics like HTTP methods as an optional feature, or causing the user to understand two different error handling models.

**Edit:** We'll still want to provide some gRPC functionality for users that are doing gRPC on the server, and want to optimize for the protobuf and gRPC semantics. We want users to fall into the HTTP+JSON path by default, but we'll provide gRPC methods as well that are clearly marked.

The changes in short:

- Invoking an HTTP service: Dapr will pass through your request as-is and perform no translation other than rewriting the URL path
- Invoking a gRPC service: Dapr will perform a set of translations similar to gRPC gateway. An incoming HTTP request will be mapped to a gRPC service call. The gRPC error code (if any) will be translated to an HTTP status code, and message body.

Since we're now committing to HTTP as the protocol for service invocation (for now), we've got a single error handling model to work with, and it makes more sense to expose .NET's HTTP types in our API.

### Goals

This proposal intends to check a few boxes:

- Keep the spirit of the existing invoke APIs: terse and simple, optimized for RPC scenarios
- Provide *something* in the box that uses the vocabulary of service invocation
- Reuse existing types where possible to support knowledge transfer

We're also merging support for using `HttpClient` in all of it's glory for Dapr service invocation - https://github.com/dapr/dotnet-sdk/pull/544. We don't need so support every possible scenario through these APIs - I expect `HttpClient` to be a good choice for many users.

We also have some non-goals:

- Build a general purpose `HttpClient` wrapper library - this is for **Dapr** service invocation only
- Abstract over HTTP as a protocol in the SDK

### Proposal

We start by exposing a new set of "building-block" APIs:

```C#
public class DaprClient
{
        public abstract HttpRequestMessage CreateInvokeMethodRequest(string appId, string methodName);

        public abstract HttpRequestMessage CreateInvokeMethodRequest(HttpMethod httpMethod, string appId, string methodName);

        public abstract HttpRequestMessage CreateInvokeMethodRequest<TRequest>(string appId, string methodName, TRequest data);

        public abstract HttpRequestMessage CreateInvokeMethodRequest<TRequest>(HttpMethod httpMethod, string appId, string methodName, TRequest data);

        public abstract Task<HttpResponseMessage> InvokeMethodWithResponseAsync(HttpRequestMessage request, CancellationToken cancellationToken = default);

        public abstract Task InvokeMethodAsync(HttpRequestMessage request, CancellationToken cancellationToken = default);

        public abstract Task<TResponse> InvokeMethodAsync<TResponse>(HttpRequestMessage request, CancellationToken cancellationToken = default);
}
```

**CreateInvokeMethodRequest**: Creates a new `HttpResponseMessage` with a URL that follows the format of a Dapr service invocation request. `request.Content` will be set to a `JsonContent` if you call the generic variant.

**InvokeMethodWithResponseAsync**: Does the HTTP, and either returns a response message without checking the status code.

**InvokeMethodAsync**: Does the HTTP and returns void deserialized response depending on the method. These check the status code and throw for non-200, as is convention for the similar methods on `HttpClient`.

These APIs make it really easy to work with `HttpRequestMessage/HttpResponseMessage` for any sort of customization that needs to be done, without us expanding the Dapr API set. You'll likely also want to reach for these methods for cases where you do error handling without exceptions.

Examples:

- Manipulating headers
- Using protobof (set `request.Content`)
- Send a request and write your own code for handling deserialization based on status code

:bulb: Note: on parameter ordering - I made the `HttpMethod` come first, and be optional for RPC-style cases. This largely follows existing APIs for HTTP (like `HttpRequestMessage`). If you think of the app id and "method" as comprising the URI, it's the same design. 

----

Next we'll want to expose the JSON serializer options

```C#
public class DaprClient
{
        public abstract JsonSerializerOptions JsonSerializerOptions { get; }
}
```

The user provided these, and so we want to make them easy to access. This is useful because we perform serialization on the user's behalf in some cases, but not every conceivable case. In some error handling cases the user might need to deserialize manually using [ReadFromJsonAsync](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.httpcontentjsonextensions.readfromjsonasync?view=net-5.0) - so we should make the options instance public.

----

Next we tweak the existing family of `InvokeMethodAsync` overloads to follow those conventions. `HttpOptions` goes away, as do `InvocationRequest` and `InvocationResponse`. We're going to use the built-in types.

```C#
public class DaprClient
{
     public Task<TResponse> InvokeMethodAsync<TRequest, TResponse>(
            string appId,
            string methodName,
            TRequest data,
            CancellationToken cancellationToken = default);

     public Task<TResponse> InvokeMethodAsync<TRequest, TResponse>(
            HttpMethod httpMethod,
            string appId,
            string methodName,
            TRequest data,
            CancellationToken cancellationToken = default);
}
```

These methods become non-abstract convenience methods that chain together calls to `CreateInvokeMethodRequest` and `InvokeMethodAsync(HttpRequestMesage request, ...)`.

We've simplified these a bit, and they no longer directly support raw bytes or header manipulation - but that's find because users can use `CreateInvokeMethodRequest` directly.

**Open Question:** Do we want a hybrid one-liner that returns an `HttpResponseMessage`? (probably not)

---

We'll retain some gRPC specific functionality and make the boundaries clear via naming.

```C#
public class DaprClient
{
        public abstract Task<InvokeMethodGrpcAsync(string appId, string method, CancellationToken cancellationToken = default);
        public abstract Task<InvokeMethodGrpcAsync<TRequest>(string appId, string method, TRequest data, CancellationToken cancellationToken = default) where TRequest : IMessage;
        public abstract Task InvokeMethodGrpcAsync<TRequest>(string appId, string method, CancellationToken cancellationToken = default)  where TResponse : IMessage;
        public abstract Task<TResponse> InvokeMethodGrpcAsync<TRequest, TResponse>(string appId, string method, TRequest data, CancellationToken cancellationToken = default)  where TRequest : IMessage where TResponse : IMessage;
}
```

**Comment by rynowak** [comment]
@amolenk - I think you were interested in this

**Comment by amolenk** [comment]
@rynowak thanks

It’s not entirely clear to me how the new HTTP invocations work. Am I correct that HTTP to HTTP service invocations still use gRPC internally in the runtime?:

```
Caller (SDK) HTTP —> Dapr Sidecar Internal gRPC —> Dapr Sidecar HTTP —> Callee
```

I can also use the new `HttpClient` support to call a gRPC service, right?

```
Caller (HttpClient) HTTP —> Dapr Sidecar Internal gRPC —> Dapr Sidecar gRPC —> Callee
```

There’s a small typo in the proposal. For the ****CreateInvokeMethodRequest** you explain that it creates a new `HttpResponseMessage`. That should be a new `HttpRequestMessage`.

I assume the non-abstract convenience methods throw for non-200 codes?

I don’t think we need a convenience method that returns an `HttpResponseMessage`. I feel like that will muddy the waters somewhat. I like how the current proposal makes a distinction between *just make a simple call* and *do any advanced stuff yourself*. 

Overall, I think this is a great improvement that will give a lot of flexibility without having to introduce new concepts to the user.

**Comment by georgestevens99** [comment]
@rynowak Thanks for your work on this.  

I am using gRPC for all my collaborating services in a greenfield development.  I chose gRPC since 1) It has faster communications than http and 2) since it supports Protobuf.  

It looks as if your changes only impact HTTP -- Is that so?  In other words, gRPC communications for Service Invocation will still be available so as to realize the 2 above listed benefits?  Thanks.

**Comment by rynowak** [comment]
>  I chose gRPC since 1) It has faster communications than http and 2) since it supports Protobuf.

How are you using gRPC? - through the `InvokeMethodAsync` APIs on `DaprClient` or are you using the gRPC client directly?

There are two changes that you should be aware of:

We're changing `InvokeMethodAsync` and similar functionality in other SDKs to use HTTP in its implementation. You can read more about the motivations for this change [here](https://github.com/dapr/dapr/issues/2342). The main thing is that its not straightforward to wrap HTTP invocations in gRPC due to differences in the error handling model - the reverse works well. This is the same reason why it's pretty obtuse to write an abstraction in code that handles both protocols. 

We're changing the `InvokeMethodAsync` family of methods to no longer perform Protobuf serialization. This is not out of a desire to remove Protobuf, but out of a desire to have absolute clarity about what serialization Dapr performs on your behalf. Having method calls that sometimes result in protobuf and sometimes result in JSON is suspect. You can read more about that change [here](https://github.com/dapr/dotnet-sdk/issues/442). I'm happy to add `InvokeMethodProtobuf<>` versions to this proposal so that functionality is still easy to access.

----

So where does this leave you:

I suppose you have the option to use the generated grpc client if you want (namespace == `Dapr.Client.Autogen.Grpc.v1`). This gets you as close to the bare metal as you can go, but I can't say its especially nice to program against.

You could also use protobuf with `DaprClient.InvokeMethodProtobufAsync` to talk to your gRPC services - this will use an HTTP error handling model - ie, rather than gRPC status codes you'll get HTTP status codes.

You could adopt HTTP as a server-side programming model with Protobuf as the serialization format.

The north star here is still to enable the actual gRPC programming model with Dapr (generated clients and servers), but that won't be happening for v1. 

----

I'm not sure that I believe the claims about performance differences between HTTP+JSON and gRPC in a vacuum. Protobuf is definitely a more compact (on the wire) format which is the source of many of these claims. However implementing Protobuf in a GC'ed language (esp. .NET) comes with some perf drawbacks that are unavoidable due to the nature of the format. 

In general if there is a benefit for your use case with Dapr, it's actually related to the serialization format, and not the underlying protocol.  Many of the other benefits of gRPC (streaming) aren't supported yet with Dapr.

**Comment by georgestevens99** [comment]
Hi Ryan,

Thanks for the detailed info. Rather than getting in the details of the
links you kindly provided, I'll instead provide you with some background
and a brief sketch of my high level requirements and why I am using Dapr in
the first place.  Then perhaps you can tell me if your changes will throw a
monkey wrench into what I am doing with Service Invocation.

I come from designing and writing services in WCF between 2011 and 2016,
using an RPC approach along with a lot of Messaging (queues) as well.  Both
RPC and Messaging used chunky DTOs (often containing an object hierarchy,
rather than just a single, flat class).  I have found using a straight RPC
approach (without having to worry about the HTTP verbs and the various http
headers) to be very highly productive for programming teams.  Specifically,
an RPC approach allows one to express the behavior of each service
operation clearly and concisely as some desired domain oriented behavior,
plus to send chunky Data Transfer Objects (again directly aimed at domain
oriented things) and to receive responses as chunky DTOs as well.

Note, I am being driven by business productivity goals, and not technology.
In my several decades of software development, the above is the most highly
productive (doing much more with less time and effort and money) way of
implementing services that I have seen. WCF excelled at it, but is no
longer an option.  Azure Service Fabric excels at it also, but is very
limited on the hosts it can run on. And recently I have been able to use
this highly productive RPC plus Messaging style with Azure Functions and
Durable Functions, but they too have fairly strict run-time-environment
limitations as well.

It is my hope that ASP.NET gRPC coupled with Dapr will support the RPC
style outlined above, plus messaging as well, AND allow me to develop
systems of collaborating services that can run literally *ANYWHERE* -- On
edge devices like IoT Edge or Azure Stack Edge, on VMs, on-prem, in the
cloud, within container orchestrators like K8s, etc.  Use the same code,
the same DTOs, and change some config files, builds, deployments, etc and
it runs!  That is what I am after.  All these possible hosts should be able
to use the same RPC plus Messaging programming model for the sake of
increasing productivity and thus decreasing the cost to the owner of the
software.

Again, in a sentence -- My goal is to be able to use ASP.NET gRPC and Dapr
(for messaging, service invocation, bindings, plus more) to be able to
develop RPC and Messaging based services in a *highly cost effective way*
that *can run almost ANYWHERE* *without having to do code changes* to get
them to run in other places.  Why? This maximizes the business value that I
can produce.  Plus having a staff that does not have to have a wide breadth
of technical skills, but rather is very highly focused on deep expertise in
a few key programming technologies.  Again, this maximizes the business
value I create for customers.

Increasing productivity and maximizing the business value for customers are
the main drivers for me using Dapr.  My intention is to use ASP.NET gRPC or
Dapr Messaging (pub/sub or queue bindings) to communicate with the single
outside-facing-service in a small collection of collaborating services
(called a subsystem).  Then my plan is to use RPC style Service Invocation
to communicate between the "outside facing service" and some or even all of
the several other services within a subsystem.

If I cannot have a clean RPC style Service Invocation for this purpose it
throws a monkey wrench into the works.  I definitely do NOT want to have to
have developers needing to be competent in both RPC and HTTP programming
(get, post, etc, http headers...).   I found the Service Invocation in RC 2
to be acceptable and it does a good job of preventing devs from having to
deal with HTTP verbs and headers in the code they write.

If I can have RPC style programming for Service Invocation, both with the
request and the response, but have to live without protobuf and use chunky
DTOs implemented in JSON for a year or two, then I can live with that.
Although I'd much rather have protobuf since it's binary format conserves
network bandwidth (which is much more difficult to scale out than compute
is).  And on the smaller Edge devices network bandwidth may be even way
more scarce than compute.

So now you know what I want and need, and I hope that you can accomodate my
needs (I'd argue that my needs are also shared by many organizations in the
.NET world right now, or soon will be when we start developing more, and
more, and more software in our quest to counteract climate change).  I also
understand the reasons why you are making the changes you are making.

Please let me know if your changes will upset my planned use of Service
Invocation.

Thanks again for your work,
George

**Comment by rynowak** [comment]
Thanks for the additional thoughts - I think the best thing to do here is to augment the proposal above with a family of `InvokeMethodGrpcAsync` methods that use Protobuf and gRPC's semantics. That will give you the same experience you have today, the only difference will be that its a different method name.

**Comment by georgestevens99** [comment]
Thanks for the quick response.  That sounds like a good plan.  It keeps
Protobuf and gRPC "in the game"  and perhaps even well positioned for the
long run when ASP.NET implementation of gRPC and Protobuf is more mature.
Plus also allows people interested in Dapr to "see what the future may look
like"!

Building new software on top of new software is always highly changeable so
I appreciate you adding the InvokeMethodGrpcAsync family of methods!
Thanks.
