### ISSUE TITLE
Dapr Examples that do not require local Dapr Installation

### ISSUE THREAD

**Issue by samcov** [dapr/dotnet-sdk#604]
It would be very useful if there were examples that utilized Dapr in a docker container instead of being globally installed on the computer.

It would simplify the job for people that want to easily add Dapr to existing docker-compose files.

One example of this is **eShopOnDapr**, which does not require Dapr to be installed. Simple examples like the ones here would be even more instructive, IMO.

eShopOnDapr: https://github.com/dotnet-architecture/eShopOnDapr

**Comment by rynowak** [comment]
Agreed. We should add this to docs, and we point summarize or point to the eshop example.

**Comment by rynowak** [comment]
I'm adding a section to the documentation about different development options for dapr. This will include a link to our central docs on docker-compose as well as a pointer to the eShopOnContainers application.

For now I'm not planning on adding a runnable sample to **this repo** because none of other apps here are good use cases for it - they are more like tests. eShop is a much better sample and I would rather point people there.

**Comment by samcov** [comment]
Sounds great!

BTW, I'm **all in on Dapr** right now. 

I've got it working perfectly in docker, running some final tests before we move on to Kubernetes testing.

You guys have a sweet product here, I hope project Tye has as much success.
