### ISSUE TITLE
the json serializer can use  Newtonsoft.Json?

### ISSUE THREAD

**Issue by a121984376** [dapr/dotnet-sdk#628]
## Ask your question here
hi~
dapr use System.Text.Json , can dapr config use Newtonsoft.Json?

**Comment by rynowak** [comment]
Dapr does not have a configurable serializer today. The underlying transports use raw bytes.

Depending on the building block its pretty easy to use your own logic, for example service invocation you can use the `HttpRequestMessage` or HttpClient directly.

We haven't tried to make this easy because there haven't been any requests for it thus now. It adds a very large amount of surface area, and I wouldn't add it without a significant amount of feedback.

**Comment by mdg215199** [comment]
It would be nice if this was an option.  Overall, System.Text.Json is great, and while i appreciate the performance there are situations where System.Text.Json can cause headaches where as newtonsoft has no issues at all.
