### ISSUE TITLE
ASP.NET + Redis + ProtocolBuffer: Invalid deserialization of repeated fields

### ISSUE THREAD

**Issue by git-torrent** [dapr/dotnet-sdk#638]
## Expected Behavior

When reading from Redis stream data like this: 

```
"subscription":{
  "msisdn":"D5B53751-E9F3-44C1-84B6-797AB98D0C13",
  "sessions":[
    {
      "ipAddress":"127.0.0.1",
      "ipAddress":"192.168.1.1"
    }
  ],
  "results":[
     {
       "category": 12,
       "category": 10
     }
  ]
},
```

This message should be de-serialized into C# generated ProtocolBuffer message with repeated fields populated.

## Actual Behavior
Instead, repeated fields are just empty as if the message were:

```
"subscription":{
  "msisdn":"D5B53751-E9F3-44C1-84B6-797AB98D0C13",
  "sessions":[  ],
  "results":[  ]
},
```

## Steps to Reproduce the Problem

1. setup the client as suggested at [Use the Dapr .NET SDK](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/publish-subscribe#use-the-dapr-net-sdk)

  In our case it is:
  ```
    public class SaveController: ControllerBase
    {
      [Topic( Constants.PubsubName, Constants.PubsubTopic )]
      [HttpPost("saveEvent")]
      public async Task<IActionResult> SaveEvent( onWebAccess event, [FromServices] DaprtClient _daprClient )
      {
        // event does not contain any of the repeated fields, so they are set to default (empty)
      }
    }
  ```

2. use configuration for Redis containing:
  ```
  spec:
    type: pubsub.redis
    version: v1
    metadata:
      name: RedistHost
      value: <address:port to your redis>
  ```

We tried different ProtocolBuffer messages and all of them have the same issue
We tried to manually insert JSON-serialized message into Redis stream - the same issue

We tried to let Dapr to publish message into Redis stream - message is properly serialized and repeated fields have content. So the bug must be on reading side.

Similar issues were reported already: 
- https://github.com/dapr/dotnet-sdk/issues/268#issuecomment-605427567
- https://github.com/dapr/dotnet-sdk/issues/268#issuecomment-665545891

even an issue was created https://github.com/PlanBGmbH/dapr-vote/issues/2
- despite marked as fixed, the bug still appears

We have not tried Any fields, but the discussion above suggest it should be buggy too.

**Comment by rynowak** [comment]
Hi @git-torrent the Dapr .NET SDK does not provide any serialization facilities directly, it calls through to either System.Text.Json or the protobuf serializer. 

> This message should be de-serialized into C# generated ProtocolBuffer message with repeated fields populated.

What's not super clear to me from your example is *what code* is attempting to deserialize the message? Are you relying on MVC model binding (`System.Text.Json`) for this? I'm confused because your example talks about protobuf but shows MVC model binding.

If I understand the issue you're describing - this is a pubsub message in JSON format, and part of it contains a repeated JSON property:

```
// snip
{
  "ipAddress":"127.0.0.1",
  "ipAddress":"192.168.1.1"
}
```

Is this a format you control or is this something externally specified?

I mention this because the semantics of a repeated property in JSON is ambiguous in the spec. Different JSON serializers will behave differently for this case. It can also be used as an attack vector: https://labs.bishopfox.com/tech-blog/an-exploration-of-json-interoperability-vulnerabilities

---

It's possible that the cloud events middleware is sanitizing the duplicate properties. https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.AspNetCore/CloudEventsMiddleware.cs#L56

I'll test this out and try to see if that's the case.

**Comment by rynowak** [comment]
I tested this out and the cloud-events middleware is passing through the duplicate properties for the case I tested.

```C#
[Fact]
        public async Task InvokeAsync_ReplacesBodyJson_DuplicatePropertyNames()
        {
            var encoding = Encoding.UTF8;
            var app = new ApplicationBuilder(null);
            app.UseCloudEvents();

            // Do verification in the scope of the middleware
            app.Run(httpContext =>
            {
                httpContext.Request.ContentType.Should().Be("application/json");
                ReadBody(httpContext.Request.Body).Should().Be("{\"name\":\"jimmy\",\"name\":\"billy\"}");
                return Task.CompletedTask;
            });

            var pipeline = app.Build();

            var context = new DefaultHttpContext();
            context.Request.ContentType = "application/cloudevents+json";
            context.Request.Body = MakeBody("{ \"datacontenttype\": \"application/json\", \"data\": {\"name\":\"jimmy\", \"name\":\"billy\"} }", encoding);

            await pipeline.Invoke(context);
        }
```

**Comment by rynowak** [comment]
Closing due to lack of response.
