### ISSUE TITLE
Support passing trace headers

### ISSUE THREAD

**Issue by FacioRatio** [dapr/dotnet-sdk#698]
Distributed tracing does not work "out of the box" and the DaprClient does not allow one to pass the "traceParent" header.

Distributed tracing requires calling the Dapr sidecar via HTTP/GPRC so that the "traceParent" can be propagated.

All calls to CreateCallOptions in DaprClientGrpc.cs explicitly set "headers: null", thus ensuring it can never be used if one wants distributed tracing.

Adding appropriate overloads to DaprClient and thus in DaprClientGrpc to accept headers would provide the bare minimum.

To remove the burden of retrieving and passing those headers from the developer, a lightweight DaprTracerClient with a scoped lifestyle and a dependency on the DaprClientGrpc singleton could be responsible for retrieving and passing the trace headers. DaprTracerClient could itself have a mechanism to allow the developer to specify which tracerParent to use on subsequent calls.

**Comment by hirensharma** [comment]
+1
I am using PubSub with .NET SDK and it is a pain

**Comment by halspang** [comment]
I was playing with this recently in an attempt to get tracing working across bindings. As it turns out, it's the dapr runtime that strips the headers. .NET's tracing infrastructure automatically applies the header and it's up to the runtime to preserve these things.

In short, there's actually no change in the .NET SDK, we're just making changes on the runtime so I'm closing this issue. If you have more questions, feel free to re-open.

**Comment by akakarikos** [comment]
@FacioRatio @halspang did you find a solution to this? I'm using the Dapr 1.9.3 and the .NET SDK but still, it seems that the traceparent header is not propagating when calling daprClient.InvokeMethodAsync().

**Comment by FacioRatio** [comment]
No @akakarikos I wrote my own little Dapr client to suit my needs. I don't use the SDK.

**Comment by akakarikos** [comment]
Ok @FacioRatio thanks!
