### ISSUE TITLE
Querying State

### ISSUE THREAD

**Issue by kamlesh-nb** [dapr/dotnet-sdk#727]
Is it possible to query the state, to get the items that are matching the filter criteria?

**Comment by rynowak** [comment]
Hi @kamlesh-nb 

This is not a feature that the state store building block provides. There's some previous discussion of this here: https://github.com/dapr/dapr/issues/1339

if you're interested in this, the right place to discuss is on dapr/dapr - since we would only add this to the SDK after it is added to the runtime.
