### ISSUE TITLE
DaprClient.InvokeMethodGrpcAsync报错 HTTPExtension

### ISSUE THREAD

**Issue by tangly1991** [dapr/dotnet-sdk#753]
## 调用代码

```C#
using var client = new DaprClientBuilder().Build();

var cts = new CancellationTokenSource();

var deposit = new Transaction() { Id = "17", Amount = 99 };
var account1 = await client.InvokeMethodGrpcAsync<Transaction, Account>("basicdata-service-api", "deposit", deposit, cts.Token);
```C#

## 错误信息
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="fail to invoke, id: basicdata-service-api, err: rpc error: code = Internal desc = error invoking app channel: rpc error: code = InvalidArgument desc = missing HTTP extension field")

使用grpc时HTTPExtension在哪里设置呢，examples项目里只有http连接的才有这个参数设置

**Comment by fbridger** [comment]
It would help if you could translate this to English and provide more context on how you are using Dapr so anyone can help you.

**Comment by GreenShadeZhang** [comment]
你需要设置应用服务的协议类别--app-protocol我是使用的docker compose 所以我在启动参数里加了这个参数。参数的顺序很重要，不然有的不生效。

You need to set the protocol category of the application service -- app protocol. I use docker compose, so I added this parameter to the startup parameters. The order of parameters is very important, otherwise some will not take effect.
```
command: [ "./daprd", "-app-id", "daprbackend", "--app-protocol" , "grpc", "-app-port", "443" ,"-components-path", "/components","--app-ssl" , "true"]
```

**Comment by halspang** [comment]
This has been quiet for a while, I'm closing the issue. @tangly1991 - Feel free to reopen if you need anything else.
