### ISSUE TITLE
WaitForSidecarAsync works only if there is a daprd.exe instance running on port 3500

### ISSUE THREAD

**Issue by francotiveron** [dapr/dotnet-sdk#871]
## Expected Behavior

DaprClient.WaitForSidecarAsync() to correctly detect sidecar 

## Actual Behavior

If there is not an instance of daprd.exe running on port 3500, it fails

## Steps to Reproduce the Problem

Debug a dapr application in VS code using the daprd task with an http dapr port different from 3500

N.B.  if a daprd.exe instance on port 3500 (also different from the one under debugging) is running, the issue disappears.
Seems related to [4557](https://github.com/dapr/dapr/issues/4557#issuecomment-1113536329)

**Comment by rynowak** [comment]
@francotiveron - I suspect what's going on in your case is that the `DAPR_HTTP_PORT` and `DAPR_GRPC_PORT` env-vars are not set. 

There's a set of environment variables that dapr sets for you when you do `dapr run ...` to launch your app. The SDK is aware of these variables and uses them to configure things like ports.  The SDK also gives you ability to set these values manually if you want to get them via some other mechanism. 

We're not experts in what the VS Code extension does here, so hopefully this explanation helps you solve the issue. @philliphoff any insights?

**Comment by francotiveron** [comment]
@rynowak The VS Code task has settings for those ports, hence I think that is not the problem

```
        {
            "label": "daprd-debug-mine",
            "type": "daprd",
            "config": ".dapr/localhost/config.yaml",
            "componentsPath": ".dapr/localhost/components",
            "appId": "yatp-mine",
            "appPort": 5162,
            "httpPort": 3500,
            "grpcPort": 50002,
            "metricsPort": 9092,
            "dependsOn": "build-mine",
            "presentation": {
                "close": true,
            }
        },
```

**Comment by halspang** [comment]
@francotiveron - I'm also not super familiar with the VSCode extension, but taking a quick look at it and the VS Code Task settings, I wonder if it's looking for the `args` and `command` values:

https://github.com/microsoft/vscode-dapr/blob/main/src/tasks/daprCommandTaskProvider.ts#L31

This makes me think that the dapr sidecar and the application are being run in separate commands which would mean that the environment variables aren't being set for the application, hence the lack of availability.

Have you tried manually setting the environment variables? It'd help to narrow this down until we can get some input from someone who knows the extension better.

**Comment by francotiveron** [comment]
@halspang Tried, no difference. The env variable gest overridden by the task settings, as expected

**Comment by halspang** [comment]
So if you add logging into your app, what does it think the env variable is?

Similarly, what does the output your `dapr list` command look like?

**Comment by philliphoff** [comment]
@francotiveron Ah, yes, @rynowak is correct.  The Dapr sidecar is started entirely independent of the .NET process being debugged, so if using the Dapr SDK and non-standard ports, you'll need to supply the same Dapr ports as environment variables to the .NET debug launch configuration as supplied to the Dapr task itself.

VS Code can't use `dapr run` for debugging because that CLI doesn't allow a pipe to be established for the debugger to communicate with the debuggee.  The VS Code API also doesn't allow for propagating the output of build tasks (such as the one that starts the Dapr sidecar) to the input of the launch configuration (that starts the .NET process and debugger), so we're often not able to do convenient things such as automatically configure environment variables of the debug process based on dynamically chosen values (e.g. ports) from a build task.

**Comment by francotiveron** [comment]
see https://github.com/dapr/docs/issues/2417
