### ISSUE TITLE
Support for .NET standard 2.0 and/or 2.1

### ISSUE THREAD

**Issue by rangers-globecar** [dapr/dotnet-sdk#925]
Is there any reason this project is not compiled against `netstandard2.0` ?   I checked all the dependencies, and they would all be compatible with `netstandard2.0`

this would enable us to use it with legacy (for example 4.8) application that are migrating....  to be able to breakout components-by-components....

**Comment by halspang** [comment]
@robert-stratecglobal - Thanks for opening this issue! However, we have no plans to support `netstandard` and have turned it down in the past. We have limited resources here and want to limit our scope to match the supported versions of .NET. `netstandard` is past LTS (so is 5.0). Though we'll retain 5.0 since we already support it and can't remove it without a breaking change, we don't want to bring on `netstandard`.

**Comment by WhitWaldo** [comment]
Closing this issue as it's been answered and there aren't any follow up questions.
